playground/Auth0.AspNetCore.Mvc.Playground/Program.cs
playground/Auth0.AspNetCore.Mvc.Playground/Startup.cs
playground/Auth0.AspNetCore.Mvc.Playground/Views/Shared/_Layout.cshtml
src/Auth0.AspNetCore.Mvc/Auth0WebAppAuthenticationBuilder.cs
src/Auth0.AspNetCore.Mvc/Auth0WebAppOptions.cs
src/Auth0.AspNetCore.Mvc/Auth0WebAppWithAccessTokenAuthenticationBuilder.cs
src/Auth0.AspNetCore.Mvc/AuthenticationBuilderExtensions.cs
src/Auth0.AspNetCore.Mvc/OpenIdConnectEventsFactory.cs
src/Auth0.AspNetCore.Mvc/ServiceCollectionExtensions.cs
src/Auth0.AspNetCore.Mvc/TokenClient.cs
src/Auth0.AspNetCore.Mvc/Utils.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Auth0MiddlewareTests.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Builders/OidcMockBuilder.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Extensions/HttpClientExtensions.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Extensions/HttpRequestMessageExtensions.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Infrastructure/TestAuthHandler.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Infrastructure/TestConfiguration.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Infrastructure/TestServerBuilder.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/TokenValidationTests.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Utils/JwtUtils.cs
tests/Auth0.AspNetCore.Mvc.IntegrationTests/Utils/UriUtils.cs

Doing a few small cleanups (e.g. unused using, fix a few XML comments) as well as adding the following changes to align with https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions:
- use `_` prefix for private fields
- Do not use `this` in constructor assignments

Use uniform code conventions

---

src/Auth0.AspNetCore.Mvc/AccessTokenResponse.cs
src/Auth0.AspNetCore.Mvc/Auth0.AspNetCore.Mvc.csproj
src/Auth0.AspNetCore.Mvc/TokenClient.cs

Replaces Newtonsoft with System.Text.Json as it's another dependency to put in the bin.
Related to #42 
Tested in my own Auth0 tenant and ensured the returned payload was valid.

Use System.Text.Json

---

src/Auth0.AspNetCore.Mvc/AccessTokenResponse.cs
src/Auth0.AspNetCore.Mvc/Auth0.AspNetCore.Mvc.csproj
src/Auth0.AspNetCore.Mvc/Auth0WebAppOptions.cs
src/Auth0.AspNetCore.Mvc/Auth0WebAppWithAccessTokenAuthenticationBuilder.cs
src/Auth0.AspNetCore.Mvc/Auth0WebAppWithAccessTokenEvents.cs
src/Auth0.AspNetCore.Mvc/Auth0WebAppWithAccessTokenOptions.cs
src/Auth0.AspNetCore.Mvc/AuthenticationBuilderExtensions.cs
src/Auth0.AspNetCore.Mvc/BaseAuthenticationPropertiesBuilder.cs
src/Auth0.AspNetCore.Mvc/IdTokenValidator.cs
src/Auth0.AspNetCore.Mvc/LoginAuthenticationPropertiesBuilder.cs
src/Auth0.AspNetCore.Mvc/LogoutAuthenticationPropertiesBuilder.cs
src/Auth0.AspNetCore.Mvc/OpenIdConnectEventsFactory.cs
src/Auth0.AspNetCore.Mvc/TokenClient.cs

Adds [C#8+ nullability coverage](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references).
I generally follow the [runtime nullability guidance](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/api-guidelines/nullability.md) as it's far more detailed than Microsoft's documentation.
Closes #42 
Nullability annotations are a compile-time assistant and thus have no runtime effects. All tests are passing.

Add Nullable reference types coverage

---

playground/Auth0.AspNetCore.Authentication.Playground/Controllers/AccountController.cs
playground/Auth0.AspNetCore.Authentication.Playground/Controllers/HomeController.cs
playground/Auth0.AspNetCore.Authentication.Playground/PlaygroundConstants.cs
playground/Auth0.AspNetCore.Authentication.Playground/Startup.cs
playground/Auth0.AspNetCore.Authentication.Playground/Views/Shared/_Layout.cshtml
playground/Auth0.AspNetCore.Authentication.Playground/appsettings.json
src/Auth0.AspNetCore.Authentication/Auth0WebAppAuthenticationBuilder.cs
src/Auth0.AspNetCore.Authentication/Auth0WebAppOptions.cs
src/Auth0.AspNetCore.Authentication/Auth0WebAppWithAccessTokenAuthenticationBuilder.cs
src/Auth0.AspNetCore.Authentication/AuthenticationBuilderExtensions.cs
src/Auth0.AspNetCore.Authentication/ServiceCollectionExtensions.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0MiddlewareTests.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Controllers/AccountController.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Infrastructure/TestServerBuilder.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/appsettings.json

This PR is a continuation of https://github.com/auth0/auth0-aspnetcore-authentication/pull/56, whose intention is to enable the possibility to configure multiple Auth0 providers (each using their own authentication scheme). This is possible when using the underlying OIDC middleware, but wasn't possible when using our SDK prior to this PR.
As it could conflict in terms of cookies, this PR also adds the ability to skip adding cookies by introducing the `skipCookieMiddleware` flag.
Also extended the playground to showcase how running multiple configurations would work.
```csharp
services
.AddAuth0WebAppAuthentication(PlaygroundConstants.AuthenticationScheme, options =>
{
options.Domain = Configuration["Auth0:Domain"];
options.ClientId = Configuration["Auth0:ClientId"];
});
services …
```

[SDK-3100] Add support for specifying scheme

---

src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj

In `Microsoft.IdentityModel.Protocols.OpenIdConnect`, a bug got introduced in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/183c04ad613b1c0355b68ad3278d5a45e5c8835b. This bug got fixed in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/d6f2b66d788195b50f2b1f700beb497851194c73 and released as part of version 6.10.2. We should ensure our users use any version equal or above 6.10.2
Closes #71
Related: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1627

Pin version of Microsoft.IdentityModel.Protocols.OpenIdConnect

---

.shiprc
src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj

This prepares the project to use ship:
- ensure ship can replace the version in csproj by using a single Version property
- add shiprc

Prepare project to integrate ship

---

src/Auth0.AspNetCore.Authentication/Auth0WebAppWithAccessTokenAuthenticationBuilder.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0MiddlewareTests.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Builders/OidcMockBuilder.cs

When RTR is disabled, Auth0 does not return a new refresh token when calling oauth/token using the refresh_grant. Therefore, we need to ensure we do not update the Refresh Token when we are not getting one back from Auth0.

[SDK-3619] Do not update refresh token when rotation is disabled

---

src/Auth0.AspNetCore.Authentication/Auth0WebAppWithAccessTokenAuthenticationBuilder.cs

Clean up to use `GetTokenValue` instead of `Items.TryGetValue`.

Use GetTokenValue instead of TryGetValue

---

src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj

When Installing `Microsoft.AspNetCore.Authentication.OpenIdConnect`, `Microsoft.IdentityModel.Protocols.OpenIdConnect` v6.10.0 is installed, which contains a memory leak that is solved in v6.12.0.
This PR ensures the latest version is used.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.12.0
https://github.com/auth0/auth0-aspnetcore-authentication/issues/86
https://github.com/auth0/auth0-aspnetcore-authentication/issues/80

Update Microsoft.IdentityModel.Protocols.OpenIdConnect dependency to avoid memory leak

---

README.md
docs-source/index.md
src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0.AspNetCore.Authentication.IntegrationTests.csproj

As .NET5 has left LTS support for a while now, we are dropping support for .NET5 in this SDK.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Drop support for .NET5

---

README.md
azure-pipelines.yml
docs-source/index.md
docs/index.html
src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj

This PR drops support for .NET Core 3.1, and adds support for .NET 7.
With .NET Core 3.1 going End of Life on 2022-12-13, we will stop supporting this version of .NET with ongoing releases.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core.

Drop .NET Core 3.1; Add .NET 7

---

src/Auth0.AspNetCore.Authentication/Auth0WebAppWithAccessTokenAuthenticationBuilder.cs

Using IOptionsMonitor has a benefit over IOptionsSnapshot where it's not re-evaluated every time it's injected. This can have some benefits in situations where the options is bound to the configuration.

Use IOptionsMonitor instead of IOptionsSnapshot

---

src/Auth0.AspNetCore.Authentication/Auth0WebAppWithAccessTokenAuthenticationBuilder.cs
src/Auth0.AspNetCore.Authentication/TokenClient.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/TokenClientTests.cs

Backchannel is always available, either provided by the user or generated by the OidcConnect library.
Therefore, the code that creates our own HttpClient was obsolete and never used.
This PR removes this.

Avoid creating HttpClient when using refresh tokens

---

src/Auth0.AspNetCore.Authentication/Auth0WebAppOptions.cs
src/Auth0.AspNetCore.Authentication/Auth0WebAppWithAccessTokenAuthenticationBuilder.cs
src/Auth0.AspNetCore.Authentication/AuthenticationBuilderExtensions.cs
src/Auth0.AspNetCore.Authentication/ServiceCollectionExtensions.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0MiddlewareTests.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Controllers/AccountController.cs

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
Add the ability to specify the cookie scheme used
Create aspnet project with custom cookie.
```csharp
services
.AddAuthentication()
.AddCookie("MyCookieScheme", () => {})
.AddAuth0WebAppAuthentication(options => {
options.CookieName = "MyCookieScheme";
});

Ensure CookieName is configurable

---

CHANGELOG.md
docs/api/Auth0.AspNetCore.Authentication.Auth0WebAppOptions.html
docs/manifest.json
docs/xrefmap.yml
package-lock.json
package.json
src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj

**Added**
- Ensure CookieName is configurable [\#98](https://github.com/auth0/auth0-aspnetcore-authentication/pull/98) ([nquandt](https://github.com/nquandt))
**Changed**
- Avoid creating HttpClient when using refresh tokens [\#95](https://github.com/auth0/auth0-aspnetcore-authentication/pull/95) ([frederikprijck](https://github.com/frederikprijck))
- Use IOptionsMonitor instead of IOptionsSnapshot [\#96](https://github.com/auth0/auth0-aspnetcore-authentication/pull/96) ([frederikprijck](https://github.com/frederikprijck))

Release 1.2.0

---

EXAMPLES.md
src/Auth0.AspNetCore.Authentication/Auth0WebAppOptions.cs
src/Auth0.AspNetCore.Authentication/IdTokenValidator.cs
src/Auth0.AspNetCore.Authentication/LoginAuthenticationPropertiesBuilder.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/TokenValidationTests.cs

Adds support for the organization name by extending the ID Token validation as follows:
If organization is set and has the org_ prefix, we expect an org_id claim
If organization is set and does not have the org_ prefix, we expect an org_name claim

Support Organization Name

---

EXAMPLES.md

minor - the link in examples had become a conglomerate URL between the rules and actions documentation hyperlink which was therefore broken
just click the hyperlinks before and after the change

EXAMPLES.md unbreak action docs hyperlink

---

EXAMPLES.md
README.md

Adds an example on how to integrate blazor server using the SDK.
Note: The link to the blazor server sample application will 404 until we make it public, which should happen somewhere next week. For the time being, the information in the example should be a good starting point.

Add example to integrate in blazor server

---

src/Auth0.AspNetCore.Authentication/AuthenticationBuilderExtensions.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0MiddlewareTests.cs

When setting the `ResponseType` explicitly, our SDK would not allow to use ClientAssertion.
This PR rectifies that.

Allow using ClientAssertion when setting ResponseType

---

src/Auth0.AspNetCore.Authentication/Auth0WebAppOptions.cs
src/Auth0.AspNetCore.Authentication/AuthenticationBuilderExtensions.cs

This PR exposes the OpenIdConnectOptions.AccessDeniedPath property to control the path to use when an access denied error is thrown from the IDP.
```cs
builder.Services
.AddAuth0WebAppAuthentication(options => {
options.Domain = builder.Configuration["Auth0:Domain"];
options.ClientId = builder.Configuration["Auth0:ClientId"];
options.AccessDeniedPath = new PathString("/Path/To/Handle/AccessDenied");
});
```

Support OpenIdConnectOptions.AccessDeniedPath

---

src/Auth0.AspNetCore.Authentication/Auth0WebAppOptions.cs
src/Auth0.AspNetCore.Authentication/AuthenticationBuilderExtensions.cs
src/Auth0.AspNetCore.Authentication/Exceptions/ApiError.cs
src/Auth0.AspNetCore.Authentication/Exceptions/ApiException.cs
src/Auth0.AspNetCore.Authentication/OpenIdConnectEventsFactory.cs
src/Auth0.AspNetCore.Authentication/PushedAuthorizationRequest/PushedAuthorizationRequestHandler.cs
src/Auth0.AspNetCore.Authentication/PushedAuthorizationRequest/PushedAuthorizationRequestResponse.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0.AspNetCore.Authentication.IntegrationTests.csproj
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0MiddlewareTests.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Builders/OidcMockBuilder.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Extensions/HttpRequestMessageExtensions.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/wellknownconfig.json
tests/Auth0.AspNetCore.Authentication.IntegrationTests/wellknownconfig_without_par.json

This PR adds support for PAR by intercepting the redirect to the IDP, and posting the parameters to the  `pushed_authorization_request_endpoint` before doing the actual redirect. It also ensures we remove every parameter from the actual redirect to `/authorize`, but ensures to add the `request_uri`.
This is needed because there is no support for PAR yet, see https://github.com/dotnet/aspnetcore/issues/51686.

Add support for Pushed Authorization Request

---

.github/workflows/build.yml
src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj

Add explicit support for .NET8 and build on CI using .NET6, 7 and 8.

Explicitly add .NET8 support

---

.github/dependabot.yml
src/Auth0.AspNetCore.Authentication/Auth0.AspNetCore.Authentication.csproj
src/Auth0.AspNetCore.Authentication/PushedAuthorizationRequest/PushedAuthorizationRequestHandler.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0.AspNetCore.Authentication.IntegrationTests.csproj
tests/Auth0.AspNetCore.Authentication.IntegrationTests/Auth0MiddlewareTests.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/BackchannelLogoutTests.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/TokenValidationTests.cs
tests/Auth0.AspNetCore.Authentication.IntegrationTests/wellknownconfig.json
tests/Auth0.AspNetCore.Authentication.IntegrationTests/wellknownconfig_without_par.json

- Upgrade version of `Microsoft.IdentityModel.Protocols.OpenIdConnect` to `8.12.1`
- Upgrade version of `System.Text.Encodings.Web` to `8.0.0`
For test cases : 
- Upgrades versions of the following
- Framework from .NET 6 to .NET 8
- `FluentAssertions` to `8.5.0`
- `Microsoft.AspNetCore.Mvc.Testing` to `8.0.*`
- `Microsoft.AspNetCore.Mvc.ViewFeatures` to `2.3.0`
- `Microsoft.NET.Test.Sdk` to `16.9.4`
- `Moq` to `4.20.72`
- `xunit` to `2.9.3`
- `xunit.runner.visualstudio` to `2.4.3`
- `coverlet.collector` to `6.0.*`
- [SDK-5567](https://auth0team.atlassian.net/browse/SDK-5567)
- Setup repository on local and run all test cases on local.
[SDK-5567]: https://auth0team.atlassian.net/browse/SDK-5567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade dependency versions and fix failing tests
